server:
  port: 8080 # ??????????? ???? ??? ?????

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # ???????? ?????????????? ???????? ?????? ?? ?????? ???? ???????? ?? Eureka
          enabled: true
      # ????????? ?????? ????????????? ???????
      routes:
        - id: subscription-service-route # ?????????? ID ?????
          # uri: ????????? ???? ????????? ??????.
          # lb:// - ????????, ??? ????? ?????? ?????? ? Eureka (lb = Load Balancer)
          # SUBSCRIPTION-SERVICE - ??? spring.application.name ?? ?????? ????????????
          uri: lb://SUBSCRIPTION-SERVICE
          # predicates: ???????, ??? ??????? ???? ???? ?????????.
          # ? ?????? ?????? - ???? ???? ??????? ?????????? ? /api/v1/subscriptions/
          predicates:
            - Path=/api/v1/subscriptions/**
