erver:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# --- ЕДИНЫЙ ПРАВИЛЬНЫЙ БЛОК 'spring' ---
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Отключаем автоматику, чтобы она нам не мешала
      discovery:
        locator:
          enabled: false

      # Настраиваем маршрут вручную
      routes:
        - id: subscription_route
          # Адрес назначения: сервис SUBSCRIPTION-SERVICE в Eureka
          uri: http://172.18.0.6
          predicates:
            # Правило сработает, если путь начинается с /subscriptions-api/
            - Path=/subscriptions-api/**
          filters:
            # "Отрезаем" /subscriptions-api от пути перед отправкой
            - StripPrefix=1