server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: subscription_service_main_route
          uri: lb://SUBSCRIPTION-SERVICE
          predicates:
            - Path=/subs/**
          filters:
            - StripPrefix=1

# --- СЕКЦИЯ ДЛЯ МАКСИМАЛЬНО ПОДРОБНЫХ ЛОГОВ ---
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE
    reactor.netty.http.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"