server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Явно отключаем автоматику, чтобы не было конфликтов
      discovery:
        locator:
          enabled: false

      # Настраиваем наш единственный маршрут
      routes:
        - id: subscription_rewrite_route
          uri: lb://SUBSCRIPTION-SERVICE
          predicates:
            # ПРАВИЛО: Срабатывать на пути, начинающиеся с /subscriptions/
            - Path=/api/**
