
# ???, ??? ??????? ?????? ???????????????? ? Eureka
spring:
  application:
    name: subscription-service

# ???? ??? ???????. 0 - ?????? Spring ??????? ????????? ????????? ????.
# ??? ???????? ????? ??????? ??????????, ????????, 8081
server:
  port: 8081

# ????????? ????? ?????? Eureka Server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # ???????????: ?????? URL ? Eureka-?????? ????????????
    hostname: localhost
